spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://user:${CONFIG_SERVICE_PASSWORD}@config:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  from: ${EMAIL_FROM:example@example.com}

backup:
  cron: "0 0 12 * * ?" # 매일 12시에 실행

remind:
  cron: "0 0 18 * * ?" # 매일 18시에 실행

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka/

logging:
  level:
    root: INFO
    com.example: DEBUG