spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://user:${CONFIG_SERVICE_PASSWORD}@config:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

backup:
  cron: "0 0 12 * * ?" # 매일 12시에 실행

remind:
  cron: "0 0 18 * * ?" # 매일 18시에 실행

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka/