#security:
#  oauth2:
#    client:
#      clientId: account-service
#      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
#      accessTokenUri: http://auth-service:5000/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server

spring:
  datasource:
    initialize: false
  data:
    mongodb:
      uri: mongodb://mongo:27017/mongo
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers, prometheus
    endpoint:
      health:
        show-details: always
      metrics:
        export:
          prometheus:
            enabled: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

server:
  port: 6000
