spring:
  datasource:
    initialize: false
  data:
    mongodb:
      uri: mongodb://mongo:27017/mongo
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          account-service: # registrationId
            provider: auth-service
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
        provider:
          auth-service:
            issuer-uri: http://auth-service:5000
            token-uri: http://auth-service:5000/oauth2/token
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:5000
          jwk-set-uri: http://auth-service:5000/oauth2/jwks

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.openfeign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers, prometheus
    endpoint:
      health:
        show-details: always
      metrics:
        export:
          prometheus:
            enabled: true

resilience4j: # 테스트 필요
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 10 # 10번째 호출부터 실패율 계산 시작(default: 100)
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5 # half open 상태에서 5번 호출이 성공하면 circuit closed 상태로 전환

server:
  port: 6000
