logging:
  level:
    org.springframework.security: INFO

eureka: # 서비스 레지스트리에 등록 안하는데 왜 있던거지
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/api/v1/users/current

spring:
  rabbitmq:
    host: rabbitmq
