spring:
  datasource:
   initialize: false
  data:
   mongodb:
     uri: mongodb://auth-mongodb:27017/authdb
     auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka

server:
  servlet:
    context-path: /uaa
  port: 5000

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.openfeign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: mappings