hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
          filters:
            - StripPrefix=0
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**,/api/v1/users/**
          filters:
            - StripPrefix=0

        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/api/v1/statistics/**
          filters:
            - StripPrefix=0

        - id: actuator-endpoints
          uri: lb://account-service
          predicates:
            - Path=/services/account/actuator/**
          filters:
            - StripPrefix=2

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8000
